package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"

	// The root package registers every rules pack, so importing it is what makes
	// rules.Versions complete.
	_ "github.com/inference-sim/blis-schemas"
	"github.com/inference-sim/blis-schemas/rules"
)

// outDir is where generated pages live, relative to the repository root. The site
// includes them with the snippets extension; nothing else should write there.
const outDir = "docs/generated"

// enumDirs are the packages whose typed string constants form a closed vocabulary.
var enumDirs = []string{
	"vocab",
	"kernel",
	"spec/model",
	"spec/deployment",
	"spec/workload",
}

type file struct {
	path    string // relative to the repository root
	content []byte
}

// generate returns every generated file, in a stable order. root is the repository root.
func generate(root string) ([]file, error) {
	var out []file
	enums, err := enumFiles(root)
	if err != nil {
		return nil, err
	}
	out = append(out, enums...)
	r, err := rulesFile(root)
	if err != nil {
		return nil, err
	}
	out = append(out, r)
	sort.Slice(out, func(i, j int) bool { return out[i].path < out[j].path })
	return out, nil
}

const header = "<!-- Generated by `go run ./internal/docgen`. Do not edit. -->\n\n"

// enumFiles writes one file per closed vocabulary: the values of every constant declared
// with that type, in declaration order. Declaration order is kept because the source
// groups related members, and an alphabetical list would scatter them.
func enumFiles(root string) ([]file, error) {
	var out []file
	for _, dir := range enumDirs {
		pkg, consts, err := typedStringConsts(filepath.Join(root, dir))
		if err != nil {
			return nil, err
		}
		types := make([]string, 0, len(consts))
		for t := range consts {
			types = append(types, t)
		}
		sort.Strings(types)
		for _, t := range types {
			var b bytes.Buffer
			b.WriteString(header)
			vals := make([]string, 0, len(consts[t]))
			for _, v := range consts[t] {
				if v == "" {
					vals = append(vals, "`\"\"`")
					continue
				}
				vals = append(vals, "`"+v+"`")
			}
			b.WriteString(strings.Join(vals, " · "))
			b.WriteString("\n")
			out = append(out, file{
				path:    filepath.ToSlash(filepath.Join(outDir, "enum", pkg+"."+t+".md")),
				content: b.Bytes(),
			})
		}
	}
	return out, nil
}

// typedStringConsts parses the non-test Go files in dir and returns, for each named type,
// the string values of the constants declared with that type explicitly.
func typedStringConsts(dir string) (string, map[string][]string, error) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", nil, err
	}
	var names []string
	for _, e := range entries {
		n := e.Name()
		if strings.HasSuffix(n, ".go") && !strings.HasSuffix(n, "_test.go") {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	pkg := ""
	out := map[string][]string{}
	for _, n := range names {
		f, err := parser.ParseFile(fset, filepath.Join(dir, n), nil, 0)
		if err != nil {
			return "", nil, err
		}
		pkg = f.Name.Name
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, s := range gd.Specs {
				vs := s.(*ast.ValueSpec)
				id, ok := vs.Type.(*ast.Ident)
				if !ok || len(vs.Values) != len(vs.Names) {
					continue
				}
				for _, v := range vs.Values {
					lit, ok := v.(*ast.BasicLit)
					if !ok || lit.Kind != token.STRING {
						continue
					}
					s, err := strconv.Unquote(lit.Value)
					if err != nil {
						return "", nil, err
					}
					out[id.Name] = append(out[id.Name], s)
				}
			}
		}
	}
	return pkg, out, nil
}

// packFields names, for each field of rules.Pack that holds version data, what a reader
// knows it as. A Pack field missing here is an error, so a field added to Pack cannot reach
// the documentation unlabelled.
var packFields = map[string]string{
	"All2AllBackends":            "`engine.all2all_backend`",
	"SPMoEBackends":              "All-to-all backends that make the MoE input sequence-parallel",
	"AllReduceBackends":          "`engine.allreduce_backend`",
	"CUDAGraphModes":             "`engine.cudagraph_mode`",
	"CacheDTypes":                "`engine.cache_dtype`, `engine.mamba_cache_dtype`, `engine.mamba_ssm_cache_dtype`",
	"MambaCacheModes":            "`engine.mamba_cache_mode`",
	"SchedulerPolicies":          "`engine.scheduling_policy`",
	"SpeculativeMethods":         "`engine.speculative.method`, `speculator.method`",
	"AsyncCompatibleSpec":        "Speculative methods that leave async scheduling enabled",
	"OffloadSpecs":               "`offload.spec`",
	"DCPCommBackends":            "`engine.dcp_comm_backend`",
	"Quantizations":              "`engine.quantization` (in-tree methods)",
	"Connectors":                 "`offload.connector`, `pd_transfer.connector` (in-tree connectors)",
	"EvictionPolicies":           "`offload.eviction_policy` (in-tree policies)",
	"CustomAllReduceWorldSizes":  "Tensor-parallel widths the custom all-reduce kernel supports",
	"DefaultDBODecodeThreshold":  "Default dual-batch-overlap threshold for a uniform-decode batch, in tokens",
	"DefaultDBOPrefillThreshold": "Default dual-batch-overlap threshold for any other batch, in tokens",
	"TritonFetchPageBytes":       "Offload page size, in bytes, at which a CPU-to-GPU fetch uses an SM-consuming kernel",
	"TritonFetchSMs":             "SMs that fetch path withholds from the forward pass",
	"CascadeAttnOptIn":           "Cascade attention is off unless requested",
}

// rulesFile writes every registered pack: its rules, with the severities each can report
// and the reason it exists, then the values it accepts.
func rulesFile(root string) (file, error) {
	var b bytes.Buffer
	b.WriteString(header)
	// Newest release first, compared numerically: as strings, 0.100.0 sorts before 0.29.0.
	versions := rules.Versions()
	sort.SliceStable(versions, func(i, j int) bool { return versionLess(versions[j], versions[i]) })
	for _, v := range versions {
		p := rules.Lookup(v)
		// Severities are read from the source of the package that defines this pack's
		// rules, so two packs that report one rule name at different severities are each
		// described correctly.
		dir, err := packDir(p)
		if err != nil {
			return file{}, err
		}
		sev, err := ruleSeverities(filepath.Join(root, dir))
		if err != nil {
			return file{}, err
		}
		fmt.Fprintf(&b, "## Engine %s\n\n", v)
		fmt.Fprintf(&b, "### Rules\n\n")
		for _, r := range p.Rules {
			s := sev[r.Name]
			if len(s) == 0 {
				return file{}, fmt.Errorf("rule %q reports through no RuleErrorf or RuleWarnf call docgen can find", r.Name)
			}
			fmt.Fprintf(&b, "`%s`\n:   *%s.* %s\n\n", r.Name, strings.Join(s, " or "), sentence(r.Because))
		}
		fmt.Fprintf(&b, "### Accepted values\n\n")
		fmt.Fprintf(&b, "| Pack field | Governs | Value |\n|---|---|---|\n")
		pv := reflect.ValueOf(*p)
		pt := pv.Type()
		for i := 0; i < pt.NumField(); i++ {
			name := pt.Field(i).Name
			if name == "Version" || name == "Rules" {
				continue
			}
			label, ok := packFields[name]
			if !ok {
				return file{}, fmt.Errorf("rules.Pack.%s has no label in docgen's packFields", name)
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", name, label, render(pv.Field(i)))
		}
		b.WriteString("\n")
	}
	return file{path: outDir + "/rules.md", content: b.Bytes()}, nil
}

// packDir returns the repository-relative directory of the package whose functions are the
// pack's rule checks. Every rule of one pack must be defined in one package.
func packDir(p *rules.Pack) (string, error) {
	const module = "github.com/inference-sim/blis-schemas/"
	dir := ""
	for _, r := range p.Rules {
		fn := runtime.FuncForPC(reflect.ValueOf(r.Check).Pointer())
		if fn == nil {
			return "", fmt.Errorf("pack %s: rule %q has no resolvable Check function", p.Version, r.Name)
		}
		// A closure's name is "<import path>.<function>.func<n>". The import path ends at
		// the first dot after its last slash.
		name := strings.TrimPrefix(fn.Name(), module)
		slash := strings.LastIndex(name, "/")
		d := name[:slash+1+strings.Index(name[slash+1:], ".")]
		if dir == "" {
			dir = d
		} else if d != dir {
			return "", fmt.Errorf("pack %s defines rules in both %s and %s", p.Version, dir, d)
		}
	}
	return filepath.FromSlash(dir), nil
}

// versionLess compares dotted version strings field by field, numerically where both
// fields are numbers.
func versionLess(a, b string) bool {
	as, bs := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(as) && i < len(bs); i++ {
		x, errX := strconv.Atoi(as[i])
		y, errY := strconv.Atoi(bs[i])
		switch {
		case errX == nil && errY == nil && x != y:
			return x < y
		case (errX != nil || errY != nil) && as[i] != bs[i]:
			return as[i] < bs[i]
		}
	}
	return len(as) < len(bs)
}

// render prints a pack value: a set as its sorted members, a scalar as itself.
func render(v reflect.Value) string {
	switch v.Kind() {
	case reflect.Map:
		if v.Type().Elem().Kind() != reflect.Bool {
			return fmt.Sprintf("(a %s, which docgen cannot render)", v.Type())
		}
		keys := v.MapKeys()
		var members []string
		for _, k := range keys {
			if v.MapIndex(k).Bool() {
				members = append(members, fmt.Sprint(k.Interface()))
			}
		}
		if v.Type().Key().Kind() == reflect.Int {
			sort.Slice(members, func(i, j int) bool {
				a, _ := strconv.Atoi(members[i])
				c, _ := strconv.Atoi(members[j])
				return a < c
			})
		} else {
			sort.Strings(members)
		}
		for i, m := range members {
			members[i] = "`" + m + "`"
		}
		return strings.Join(members, " ")
	default:
		return "`" + fmt.Sprint(v.Interface()) + "`"
	}
}

// ruleSeverities scans one package's non-test files for RuleErrorf and RuleWarnf calls whose
// first argument is a rule name, and returns the severities each name can report.
func ruleSeverities(dir string) (map[string][]string, error) {
	found := map[string]map[string]bool{}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		path := filepath.Join(dir, e.Name())
		if e.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if err != nil {
			return nil, err
		}
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok || len(call.Args) == 0 {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			var s string
			switch sel.Sel.Name {
			case "RuleErrorf":
				s = "error"
			case "RuleWarnf":
				s = "warning"
			default:
				return true
			}
			lit, ok := call.Args[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return true
			}
			name, err := strconv.Unquote(lit.Value)
			if err != nil {
				return true
			}
			if found[name] == nil {
				found[name] = map[string]bool{}
			}
			found[name][s] = true
			return true
		})
	}
	out := map[string][]string{}
	for name, set := range found {
		for _, s := range []string{"error", "warning"} {
			if set[s] {
				out[name] = append(out[name], s)
			}
		}
	}
	return out, nil
}

// sentence capitalizes a Because clause and ends it with a period, since the source
// writes each as a clause that follows "because".
func sentence(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return s
	}
	s = strings.ToUpper(s[:1]) + s[1:]
	if !strings.HasSuffix(s, ".") {
		s += "."
	}
	return s
}
